"""add_ai_email_fields

Revision ID: 15459b2a1973
Revises: e7afc37a0dd8
Create Date: 2026-05-31 13:14:35.551745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15459b2a1973'
down_revision: Union[str, Sequence[str], None] = 'e7afc37a0dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('category', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'deadline')
    op.drop_column('emails', 'category')
    op.drop_column('emails', 'priority')
    # ### end Alembic commands ###
